require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'linktest' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'QKMRZScanner'

  target 'linktestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
